version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: symfony_php
    volumes:
      - .:/var/www/symfony
    working_dir: /var/www/symfony
    depends_on:
      - db
    networks:
      - symfony_net

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/symfony
    depends_on:
      - php
    networks:
      - symfony_net

  db:
    image: mysql:5.7
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    networks:
      - symfony_net

networks:
  symfony_net:
    driver: bridge
