version: '3'

services:
  jenkins:
    image: seqqal/jenkins-symfony:latest
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      - JENKINS_HOME=/var/jenkins_home
      - PHP_VERSION=8.2
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./symfony:/var/www/symfony
    restart: unless-stopped
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins_home:
    driver: local
